# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: npm
    directories:
      - /src/vscode-bicep
      - /src/playground
      - /src/Bicep.Cli.E2eTests
      - /src/Bicep.MSBuild.E2eTests
      - /src/textmate
      - /src/highlightjs
      - /src/monarch
    schedule:
      interval: weekly
    ignore:
      # we're deliberately taking a dependency on an older version of vscode for back-compatibility
      - dependency-name: "@types/vscode"
        versions:
          - ">1.52.0"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
