name: Build

on:
  push:
    branches: [ radius-compiler ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Publish Bicep (Linux)
      run: dotnet publish --configuration Release --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -r 'linux-x64' ./src/Bicep.Cli/Bicep.Cli.csproj -o ./artifacts/bicep/linux-x64
    - name: Publish Bicep (MacOS)
      run: dotnet publish --configuration Release --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -r 'osx-x64' ./src/Bicep.Cli/Bicep.Cli.csproj -o ./artifacts/bicep/macos-x64
    - name: Publish Bicep (Windows)
      run: dotnet publish --configuration Release --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -r 'win-x64' ./src/Bicep.Cli/Bicep.Cli.csproj -o ./artifacts/bicep/windows-x64
    - name: Publish Language Server
      run: dotnet publish "./../Bicep.LangServer" -o "./bicepLanguageServer"
      working-directory: ./src/vscode-bicep
    - name: Publish VSIX
      run: npm ci && npm run package
      working-directory: ./src/vscode-bicep
    - name: Copy VSIX
      run: mkdir -p ./artifacts/vscode && cp ./src/vscode-bicep/vscode-bicep.vsix ./artifacts/vscode/rad-vscode-bicep.vsix
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: ./artifacts

  publish:
    name: Publish 
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: artifacts
    - name: Display artifacts
      run: ls -R
      working-directory: ./artifacts
    - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      name: Upload rad-bicep (Linux)
      with:
        container_name: ${{ secrets.ASSETS_STORAGE_CONTAINER }}
        connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
        source_dir: ./artifacts/bicep/linux-x64/
        extra_args: '--destination-path ./bicep/edge/linux-x64/ --pattern rad-bicep'
        sync: true
    - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      name: Upload rad-bicep (MacOS)
      with:
        container_name: ${{ secrets.ASSETS_STORAGE_CONTAINER }}
        connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
        source_dir: ./artifacts/bicep/macos-x64/
        extra_args: '--destination-path ./bicep/edge/macos-x64/ --pattern rad-bicep'
        sync: true
    - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      name: Upload rad-bicep (Windows)
      with:
        container_name: ${{ secrets.ASSETS_STORAGE_CONTAINER }}
        connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
        source_dir: ./artifacts/bicep/windows-x64/
        extra_args: '--destination-path ./bicep/edge/windows-x64/ --pattern rad-bicep.exe'
        sync: true
    - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      name: Upload rad-bicep (Linux)
      with:
        container_name: ${{ secrets.ASSETS_STORAGE_CONTAINER }}
        connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
        source_dir: ./artifacts/vscode/
        extra_args: '--destination-path ./vscode/edge/'
        sync: true